# FONT CONFIG
font_family JetBrainsMono Nerd Font
font_size 14.0

symbol_map U+4E00-U+9FFF,U+3400-U+4DBF,U+20000-U+2A6DF,U+F900-U+FAFF Noto Sans CJK TC

# BACKGROUND CONFIG
background_opacity 0.90
background_blur 1

# CURSOR CONFIG
cursor_shape block
cursor_blink_interval 0
cursor_trail 1
# avoid shell_integration `beam` override
shell_integration no-cursor

# KEYBOARD SHORTCUTS CONFIG
map ctrl+backspace send_text all \x17

# WINDOW LAYOUT CONFIG
window_padding_width 3

# BEGIN_KITTY_THEME
# Ayu
include current-theme.conf
# END_KITTY_THEME
